name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Default Scheme
        run: |
          cd Now\ Dribble
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build
        run: |
          cd Now\ Dribble
          if [ -f default ]; then scheme=$(cat default); else scheme=default; fi
          file_to_build="Now Dribble.xcodeproj" # Adjust if needed
          # Specify a generic iPhone simulator
          destination='generic/platform=iOS Simulator'
          xcodebuild clean build analyze -scheme "$scheme" -project "$file_to_build" -destination "$destination" | xcpretty && exit ${PIPESTATUS[0]}
